"""Central configuration shared by every pipeline step."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "raw"
PROCESSED_DIR = ROOT / "data" / "processed"
MODELS_DIR = ROOT / "models"
REPORTS_DIR = ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"            # figures used by the report and slides (tracked)
RESULTS_DIR = REPORTS_DIR / "results"            # small summary tables cited in the report (tracked)
ARTIFACTS_DIR = ROOT / "artifacts"               # intermediate files and logs, regenerated by the pipeline (not tracked)
SAMPLES_DIR = ROOT / "docs" / "sample_responses"

SEED = 42

# Simulation window
START_DATE = "2024-01-01"
END_DATE = "2025-12-31"

# Prediction target: unscheduled removal within the next N flight cycles
HORIZON_FC = 30

# Business constraint from the brief
MAX_ALERT_RATE = 0.05   # <= 5 alerts per 100 active components
MIN_RECALL = 0.80       # >= 80% of actual removals detected

# Part-number sensor baselines are computed only from this early window, which always sits inside
# the training period, so fleet statistics never contain future data.
BASELINE_END = "2024-03-31"
